### ISSUE TITLE
Aurora module usage

### ISSUE THREAD

**Issue by xj78** [deliveryhero/tf-aws-rds-aurora#21]
Hi, I'm trying to create 1 writer and 2 readers but as I give a value to var.repkica_count, I get error that the argument is not expected here. Please can you advise

**Comment by max-rocket-internet** [comment]
@xj78 try `replica_count` instead of `repkica_count`?

**Comment by xj78** [comment]
Lol...it was a typo...sorted though. Thanks anyway
